# Generated by Django 4.1 on 2022-08-17 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tit', models.CharField(max_length=255)),
                ('ekriven', models.CharField(default='Nicodem LAURORE', max_length=100)),
                ('kontni', models.TextField(max_length=5000)),
                ('dat_piblikasyon', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
