# Generated by Django 4.1 on 2022-08-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atik',
            options={'verbose_name': 'Atik la', 'verbose_name_plural': 'Atik yo'},
        ),
        migrations.AddField(
            model_name='atik',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
