# Generated by Django 4.1 on 2022-08-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_depatman'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depatman',
            options={'verbose_name': 'depatman', 'verbose_name_plural': 'depatman yo'},
        ),
    ]
