# Generated by Django 4.1 on 2022-08-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_depatman_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='atik',
            name='email',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atik',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='atik',
            name='tit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='depatman',
            name='slug',
            field=models.SlugField(blank=True, max_length=45, null=True),
        ),
    ]
