# Generated by Django 4.1 on 2022-08-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_atik_email_alter_atik_slug_alter_atik_tit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atik',
            name='email',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
