# Generated by Django 4.1 on 2022-08-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_atik_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='depatman',
            name='publik',
            field=models.BooleanField(default=False),
        ),
    ]
