# Generated by Django 4.1 on 2022-08-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_depatman_publik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depatman',
            name='publik',
        ),
        migrations.AddField(
            model_name='atik',
            name='publik',
            field=models.BooleanField(default=False),
        ),
    ]
