# Generated by Django 4.1 on 2022-08-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_remove_depatman_publik_atik_publik'),
    ]

    operations = [
        migrations.DeleteModel(
            name='depatman',
        ),
        migrations.RemoveField(
            model_name='atik',
            name='ekriven',
        ),
        migrations.AddField(
            model_name='atik',
            name='Ote',
            field=models.CharField(default='Gadeley', max_length=100),
        ),
    ]
