# Generated by Django 4.1 on 2022-09-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_delete_depatman_remove_atik_ekriven_atik_ote'),
    ]

    operations = [
        migrations.AddField(
            model_name='atik',
            name='total_vizit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='atik',
            name='Ote',
            field=models.CharField(default='', max_length=100),
        ),
    ]
